In [1]:
import numpy as np

The BASICS

In [2]:
a=np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
#To get dimension of the array we use 
print(a.ndim)
print(b.ndim)

1
2


In [7]:
#To get the size of the array we use
print(a.shape)
print(b.shape)  

(3,)
(2, 3)


In [8]:
# TO get  the type of the array we use
print(a.dtype)
print(b.dtype)

int64
float64


Here the size occupied by three integers are 64 so we can change the byte size as how small we need

In [10]:
a=np.array([1, 2, 3],dtype="int16")
print(a)

[1 2 3]


In [12]:
# To get  the type of the array we use
print(a.dtype)
print(b.dtype)

int16
float64


In [13]:
#To get the item size of the array we use
print(a.itemsize)
print(b.itemsize)

2
8


In [14]:
#To get the total size of the array we use
print(a.nbytes) 

6
